"""initial schema

Revision ID: 4978fa9bc8aa
Revises: 
Create Date: 2026-07-07 19:16:00.247374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4978fa9bc8aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', 'entity_type', name='uq_entity')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_normalized_name'), 'entities', ['normalized_name'], unique=False)
    op.create_table('monitoring_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('sources_checked', sa.Integer(), nullable=False),
    sa.Column('sources_failed', sa.Integer(), nullable=False),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('items_prefiltered_out', sa.Integer(), nullable=False),
    sa.Column('items_analyzed', sa.Integer(), nullable=False),
    sa.Column('items_high', sa.Integer(), nullable=False),
    sa.Column('items_medium', sa.Integer(), nullable=False),
    sa.Column('items_low', sa.Integer(), nullable=False),
    sa.Column('alerts_sent', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('telegram_summary', sa.Text(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_type_period', 'reports', ['report_type', 'period_end'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('feed_url', sa.String(length=1000), nullable=True),
    sa.Column('fetch_method', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('authority_rank', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('robots_ok', sa.Boolean(), nullable=False),
    sa.Column('fetch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('duplicate_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=300), nullable=False),
    sa.Column('earliest_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('most_authoritative_source_id', sa.Integer(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('confidence_boosted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['most_authoritative_source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_groups_event_key'), 'duplicate_groups', ['event_key'], unique=False)
    op.create_table('raw_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1500), nullable=False),
    sa.Column('canonical_url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_norm_hash', sa.String(length=64), nullable=False),
    sa.Column('title_simhash', sa.String(length=20), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('prefilter_score', sa.Float(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_items_canonical_url_hash'), 'raw_items', ['canonical_url_hash'], unique=True)
    op.create_index('ix_raw_items_published_at', 'raw_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_raw_items_source_id'), 'raw_items', ['source_id'], unique=False)
    op.create_index('ix_raw_items_status', 'raw_items', ['status'], unique=False)
    op.create_index(op.f('ix_raw_items_title_norm_hash'), 'raw_items', ['title_norm_hash'], unique=False)
    op.create_index(op.f('ix_raw_items_title_simhash'), 'raw_items', ['title_simhash'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic', name='uq_user_topic')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('intelligence_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1500), nullable=False),
    sa.Column('all_source_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('vessel_type', sa.String(length=30), nullable=False),
    sa.Column('update_type', sa.String(length=30), nullable=False),
    sa.Column('companies_mentioned', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('vessels_mentioned', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('imo_numbers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('shipowners', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('operators', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('charterers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('insurers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('brokers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('regulators', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ports', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('shipyards', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('key_facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('impact_on_oil_transportation', sa.Text(), nullable=True),
    sa.Column('impact_on_pi', sa.Text(), nullable=True),
    sa.Column('impact_on_hm', sa.Text(), nullable=True),
    sa.Column('impact_on_war_risk', sa.Text(), nullable=True),
    sa.Column('sanctions_or_compliance_implications', sa.Text(), nullable=True),
    sa.Column('practical_business_implications', sa.Text(), nullable=True),
    sa.Column('recommended_review_points', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('report_tables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('materiality', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('classification', sa.String(length=60), nullable=False),
    sa.Column('duplicate_group_id', sa.Integer(), nullable=True),
    sa.Column('primary_raw_item_id', sa.Integer(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_group_id'], ['duplicate_groups.id'], ),
    sa.ForeignKeyConstraint(['primary_raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intel_materiality', 'intelligence_items', ['materiality'], unique=False)
    op.create_index('ix_intel_publication_date', 'intelligence_items', ['publication_date'], unique=False)
    op.create_index('ix_intel_update_type', 'intelligence_items', ['update_type'], unique=False)
    op.create_index('ix_intel_vessel_type', 'intelligence_items', ['vessel_type'], unique=False)
    op.create_index(op.f('ix_intelligence_items_duplicate_group_id'), 'intelligence_items', ['duplicate_group_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intelligence_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['intelligence_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intelligence_item_id', 'user_id', 'alert_type', name='uq_alert_once')
    )
    op.create_index(op.f('ix_alerts_intelligence_item_id'), 'alerts', ['intelligence_item_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('intelligence_item_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intelligence_item_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['intelligence_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intelligence_item_id', 'entity_id', name='uq_item_entity')
    )
    op.create_index(op.f('ix_intelligence_item_entities_entity_id'), 'intelligence_item_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_intelligence_item_entities_intelligence_item_id'), 'intelligence_item_entities', ['intelligence_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intelligence_item_entities_intelligence_item_id'), table_name='intelligence_item_entities')
    op.drop_index(op.f('ix_intelligence_item_entities_entity_id'), table_name='intelligence_item_entities')
    op.drop_table('intelligence_item_entities')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_intelligence_item_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_intelligence_items_duplicate_group_id'), table_name='intelligence_items')
    op.drop_index('ix_intel_vessel_type', table_name='intelligence_items')
    op.drop_index('ix_intel_update_type', table_name='intelligence_items')
    op.drop_index('ix_intel_publication_date', table_name='intelligence_items')
    op.drop_index('ix_intel_materiality', table_name='intelligence_items')
    op.drop_table('intelligence_items')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_raw_items_title_simhash'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_title_norm_hash'), table_name='raw_items')
    op.drop_index('ix_raw_items_status', table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_source_id'), table_name='raw_items')
    op.drop_index('ix_raw_items_published_at', table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_canonical_url_hash'), table_name='raw_items')
    op.drop_table('raw_items')
    op.drop_index(op.f('ix_duplicate_groups_event_key'), table_name='duplicate_groups')
    op.drop_table('duplicate_groups')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_reports_type_period', table_name='reports')
    op.drop_table('reports')
    op.drop_table('monitoring_runs')
    op.drop_index(op.f('ix_entities_normalized_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
