"""russian publication fields

Revision ID: d3e0d9412e65
Revises: 4978fa9bc8aa
Create Date: 2026-07-07 19:54:41.599029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3e0d9412e65'
down_revision: Union[str, Sequence[str], None] = '4978fa9bc8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intelligence_items', sa.Column('headline_ru', sa.Text(), nullable=True))
    op.add_column('intelligence_items', sa.Column('summary_ru', sa.Text(), nullable=True))
    op.add_column('intelligence_items', sa.Column('key_facts_ru', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('intelligence_items', sa.Column('why_it_matters_ru', sa.Text(), nullable=True))
    op.add_column('intelligence_items', sa.Column('impact_on_oil_transportation_ru', sa.Text(), nullable=True))
    op.add_column('intelligence_items', sa.Column('impact_on_pi_ru', sa.Text(), nullable=True))
    op.add_column('intelligence_items', sa.Column('impact_on_hm_ru', sa.Text(), nullable=True))
    op.add_column('intelligence_items', sa.Column('impact_on_war_risk_ru', sa.Text(), nullable=True))
    op.add_column('intelligence_items', sa.Column('sanctions_or_compliance_implications_ru', sa.Text(), nullable=True))
    op.add_column('intelligence_items', sa.Column('practical_business_implications_ru', sa.Text(), nullable=True))
    op.add_column('intelligence_items', sa.Column('recommended_review_points_ru', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('intelligence_items', sa.Column('publication_ready_ru', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('reports', sa.Column('content_md_en', sa.Text(), nullable=False, server_default=''))
    op.add_column('reports', sa.Column('content_md_ru', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('generated_language_versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('reports', sa.Column('telegram_summary_ru', sa.Text(), nullable=True))
    op.execute("UPDATE reports SET content_md_en = content_md")
    op.drop_column('reports', 'content_md')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('content_md', sa.TEXT(), nullable=False))
    op.drop_column('reports', 'telegram_summary_ru')
    op.drop_column('reports', 'generated_language_versions')
    op.drop_column('reports', 'content_md_ru')
    op.drop_column('reports', 'content_md_en')
    op.drop_column('intelligence_items', 'publication_ready_ru')
    op.drop_column('intelligence_items', 'recommended_review_points_ru')
    op.drop_column('intelligence_items', 'practical_business_implications_ru')
    op.drop_column('intelligence_items', 'sanctions_or_compliance_implications_ru')
    op.drop_column('intelligence_items', 'impact_on_war_risk_ru')
    op.drop_column('intelligence_items', 'impact_on_hm_ru')
    op.drop_column('intelligence_items', 'impact_on_pi_ru')
    op.drop_column('intelligence_items', 'impact_on_oil_transportation_ru')
    op.drop_column('intelligence_items', 'why_it_matters_ru')
    op.drop_column('intelligence_items', 'key_facts_ru')
    op.drop_column('intelligence_items', 'summary_ru')
    op.drop_column('intelligence_items', 'headline_ru')
    # ### end Alembic commands ###
